# cms tools

- name: Install wp-cli packages
  shell: "wp package install {{ item }}"
  with_items:
    - 10up/mu-migration
    - aaemnnosttv/wp-cli-http-command
    - aaemnnosttv/wp-cli-login-command
    - binarygary/db-checkpoint
    - danielbachhuber/wp-cli-stat-command
    - eriktorsner/wp-checksum
    - iandunn/wp-cli-plugin-active-on-sites
    - iandunn/wp-cli-rename-db-prefix
    - markri/wp-sec
    - pantheon-systems/wp_launch_check
    - petenelson/wp-cli-size
