- name: /etc/fstab entry for bash
  lineinfile:
    dest: /etc/fstab
    line: 'fdesc	/dev/fd		fdescfs		rw	0	0'

- name: Install system/dev Packages
  pkgng: name={{ item }} state=present
  with_items:
    - colordiff
    - curl
    - gettext
    - git
    - gmake
    - graphviz
    - ImageMagick7-nox11
    - ngrep
    - node
    - npm
    - libiconv
    - sqlite3
    - subversion
    - sudo
    - vim

- name: Install LEMP Packages
  pkgng: name={{ item }} state=present
  with_items:
    - mariadb101-client
    - mariadb101-server
    - nginx
    - php70
    - php70-bcmath 
    - php70-bz2 
    - php70-calendar 
    - php70-ctype
    - php70-exif 
    - php70-fileinfo 
    - php70-filter 
    - php70-ftp 
    - php70-gd 
    - php70-gettext 
    - php70-hash
    - php70-iconv 
    - php70-imap
    - php70-intl
    - php70-json
    - php70-mbstring
    - php70-mcrypt
    - php70-mysqli
    - php70-opcache
    - php70-openssl
    - php70-pcntl
    - php70-pdo
    - php70-pdo_sqlite
    - php70-posix
    - php70-phar
    - php70-readline
    - php70-redis
    - php70-session
    - php70-simplexml
    - php70-sockets
    - php70-sqlite3
    - php70-tokenizer
    - php70-xml
    - php70-xmlrpc
    - php70-xmlreader
    - php70-xmlwriter
    - php70-xsl
    - php70-zip
    - php70-zlib

- name: Install PHP Composer
  get_url: 
    url: https://getcomposer.org/download/1.2.3/composer.phar
    dest: /usr/local/bin/composer
    mode: 0755
    checksum: sha256:3378c1422bffa09c29714aefd3240b963ce7731e71ae8894d9c7991101325cb8

- name: Install WP-CLI
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 0755
    checksum: sha256:974997f6dc49750598aad8f519c29b33880032a73ada7a9bcc2a299bbe034819

- name: Ensures Nginx custom-sites dir exists
  file:
    path: /usr/local/etc/nginx/custom-sites/
    state: directory
    mode: 0755

- name: Ensures Nginx SSL dir exists
  file:
    path: /usr/local/etc/nginx/ssl/
    state: directory
    mode: 0755

- name: Ensures Nginx docroot dir exists
  file:
    path: /srv/www/
    state: directory
    mode: 0755

- name: Ensures Nginx default vhost dir exists
  file:
    path: /srv/www/default/
    state: directory
    mode: 0755

- name: create Nginx self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=EU/ST=Somewhere/L=Desk/O=EU/CN=zzz.dev" -days 3650 -keyout /usr/local/etc/nginx/ssl/server.key -out /usr/local/etc/nginx/ssl/server.crt -extensions v3_ca 
  #creates: /usr/local/etc/nginx/ssl/server.crt
  #notify: reload nginx

- name: Copy Nginx configuration
  copy:
    src: nginx.conf 
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: 0644
    backup: yes

- name: Copy Nginx/WordPress configuration
  copy:
    src: nginx-wp-common.conf 
    dest: /usr/local/etc/nginx/nginx-wp-common.conf
    owner: root
    group: wheel
    mode: 0644
    backup: yes

- name: Copy default vhost config
  copy:
    src: sites/default.conf
    dest: /usr/local/etc/nginx/custom-sites/
    owner: root
    group: wheel
    mode: 0644

- name: Enable Nginx
  command: sysrc nginx_enable="YES"

- name: Enable PHP-FPM
  command: sysrc php_fpm_enable="YES"

- name: Enable MariaDB
  command: sysrc mysql_server_enable="YES"
  