- name: /etc/fstab entry for bash
  lineinfile:
    dest: /etc/fstab
    line: 'fdesc	/dev/fd		fdescfs		rw	0	0'

- name: Install system/dev Packages
  pkgng: name={{ item }} state=present
  with_items:
    - colordiff
    - curl
    - gettext
    - git
    - gmake
    - graphviz
    - ImageMagick7-nox11
    - ngrep
    - node
    - npm
    - libiconv
    - sqlite3
    - subversion
    - vim

- name: Install LEMP Packages
  pkgng: name={{ item }} state=present
  with_items:
    - mariadb101-client
    - mariadb101-server
    - nginx
    - php70
    - php70-bcmath 
    - php70-bz2 
    - php70-calendar 
    - php70-ctype
    - php70-exif 
    - php70-fileinfo 
    - php70-filter 
    - php70-ftp 
    - php70-gd 
    - php70-gettext 
    - php70-hash
    - php70-iconv 
    - php70-imap
    - php70-intl
    - php70-json
    - php70-mbstring
    - php70-mcrypt
    - php70-mysqli
    - php70-opcache
    - php70-openssl
    - php70-pcntl
    - php70-pdo
    - php70-pdo_sqlite
    - php70-posix
    - php70-phar
    - php70-readline
    - php70-redis
    - php70-session
    - php70-simplexml
    - php70-sockets
    - php70-sqlite3
    - php70-tokenizer
    - php70-xml
    - php70-xmlrpc
    - php70-xmlreader
    - php70-xmlwriter
    - php70-xsl
    - php70-zip
    - php70-zlib

- name: Enable Nginx
  command: sysrc nginx_enable="YES"

- name: Enable PHP-FPM
  command: sysrc php_fpm_enable="YES"

- name: Enable MariaDB
  command: sysrc mysql_server_enable="YES"
  